services:
  - type: web
    name: nayarhydhm-backend
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: NVIDIA_API_KEY
        sync: false
      - key: NVIDIA_API_URL
        value: https://integrate.api.nvidia.com/v1/chat/completions
